// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: storage/storage.proto

package storage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaseRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CaseId             string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`                                        // Mã vụ án (Key) - Ví dụ: VA_2026_001
	CaseDataJson       string                 `protobuf:"bytes,2,opt,name=case_data_json,json=caseDataJson,proto3" json:"case_data_json,omitempty"`                    // Toàn bộ thông tin vụ án dạng JSON (Value)
	IsReplicationRoute bool                   `protobuf:"varint,3,opt,name=is_replication_route,json=isReplicationRoute,proto3" json:"is_replication_route,omitempty"` // Cờ đánh dấu luồng đồng bộ giữa các đồn
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CaseRequest) Reset() {
	*x = CaseRequest{}
	mi := &file_storage_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaseRequest) ProtoMessage() {}

func (x *CaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaseRequest.ProtoReflect.Descriptor instead.
func (*CaseRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

func (x *CaseRequest) GetCaseDataJson() string {
	if x != nil {
		return x.CaseDataJson
	}
	return ""
}

func (x *CaseRequest) GetIsReplicationRoute() bool {
	if x != nil {
		return x.IsReplicationRoute
	}
	return false
}

type GetCaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseId        string                 `protobuf:"bytes,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseRequest) Reset() {
	*x = GetCaseRequest{}
	mi := &file_storage_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseRequest) ProtoMessage() {}

func (x *GetCaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseRequest.ProtoReflect.Descriptor instead.
func (*GetCaseRequest) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{1}
}

func (x *GetCaseRequest) GetCaseId() string {
	if x != nil {
		return x.CaseId
	}
	return ""
}

type GetCaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaseDataJson  string                 `protobuf:"bytes,1,opt,name=case_data_json,json=caseDataJson,proto3" json:"case_data_json,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaseResponse) Reset() {
	*x = GetCaseResponse{}
	mi := &file_storage_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaseResponse) ProtoMessage() {}

func (x *GetCaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaseResponse.ProtoReflect.Descriptor instead.
func (*GetCaseResponse) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{2}
}

func (x *GetCaseResponse) GetCaseDataJson() string {
	if x != nil {
		return x.CaseDataJson
	}
	return ""
}

func (x *GetCaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_storage_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_storage_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_storage_storage_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_storage_storage_proto protoreflect.FileDescriptor

const file_storage_storage_proto_rawDesc = "" +
	"\n" +
	"\x15storage/storage.proto\x12\astorage\"~\n" +
	"\vCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\x12$\n" +
	"\x0ecase_data_json\x18\x02 \x01(\tR\fcaseDataJson\x120\n" +
	"\x14is_replication_route\x18\x03 \x01(\bR\x12isReplicationRoute\")\n" +
	"\x0eGetCaseRequest\x12\x17\n" +
	"\acase_id\x18\x01 \x01(\tR\x06caseId\"Q\n" +
	"\x0fGetCaseResponse\x12$\n" +
	"\x0ecase_data_json\x18\x01 \x01(\tR\fcaseDataJson\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x88\x01\n" +
	"\x14PoliceStorageService\x122\n" +
	"\aPutCase\x12\x14.storage.CaseRequest\x1a\x11.storage.Response\x12<\n" +
	"\aGetCase\x12\x17.storage.GetCaseRequest\x1a\x18.storage.GetCaseResponseB\vZ\t./storageb\x06proto3"

var (
	file_storage_storage_proto_rawDescOnce sync.Once
	file_storage_storage_proto_rawDescData []byte
)

func file_storage_storage_proto_rawDescGZIP() []byte {
	file_storage_storage_proto_rawDescOnce.Do(func() {
		file_storage_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)))
	})
	return file_storage_storage_proto_rawDescData
}

var file_storage_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_storage_proto_goTypes = []any{
	(*CaseRequest)(nil),     // 0: storage.CaseRequest
	(*GetCaseRequest)(nil),  // 1: storage.GetCaseRequest
	(*GetCaseResponse)(nil), // 2: storage.GetCaseResponse
	(*Response)(nil),        // 3: storage.Response
}
var file_storage_storage_proto_depIdxs = []int32{
	0, // 0: storage.PoliceStorageService.PutCase:input_type -> storage.CaseRequest
	1, // 1: storage.PoliceStorageService.GetCase:input_type -> storage.GetCaseRequest
	3, // 2: storage.PoliceStorageService.PutCase:output_type -> storage.Response
	2, // 3: storage.PoliceStorageService.GetCase:output_type -> storage.GetCaseResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_storage_proto_init() }
func file_storage_storage_proto_init() {
	if File_storage_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_storage_proto_rawDesc), len(file_storage_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_storage_proto_goTypes,
		DependencyIndexes: file_storage_storage_proto_depIdxs,
		MessageInfos:      file_storage_storage_proto_msgTypes,
	}.Build()
	File_storage_storage_proto = out.File
	file_storage_storage_proto_goTypes = nil
	file_storage_storage_proto_depIdxs = nil
}
