// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: storage/storage.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoliceStorageService_PutCase_FullMethodName = "/storage.PoliceStorageService/PutCase"
	PoliceStorageService_GetCase_FullMethodName = "/storage.PoliceStorageService/GetCase"
)

// PoliceStorageServiceClient is the client API for PoliceStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PoliceStorageServiceClient interface {
	// Hàm ghi/đồng bộ hồ sơ vụ án
	PutCase(ctx context.Context, in *CaseRequest, opts ...grpc.CallOption) (*Response, error)
	// Hàm truy xuất hồ sơ vụ án
	GetCase(ctx context.Context, in *GetCaseRequest, opts ...grpc.CallOption) (*GetCaseResponse, error)
}

type policeStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoliceStorageServiceClient(cc grpc.ClientConnInterface) PoliceStorageServiceClient {
	return &policeStorageServiceClient{cc}
}

func (c *policeStorageServiceClient) PutCase(ctx context.Context, in *CaseRequest, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PoliceStorageService_PutCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policeStorageServiceClient) GetCase(ctx context.Context, in *GetCaseRequest, opts ...grpc.CallOption) (*GetCaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaseResponse)
	err := c.cc.Invoke(ctx, PoliceStorageService_GetCase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoliceStorageServiceServer is the server API for PoliceStorageService service.
// All implementations must embed UnimplementedPoliceStorageServiceServer
// for forward compatibility.
type PoliceStorageServiceServer interface {
	// Hàm ghi/đồng bộ hồ sơ vụ án
	PutCase(context.Context, *CaseRequest) (*Response, error)
	// Hàm truy xuất hồ sơ vụ án
	GetCase(context.Context, *GetCaseRequest) (*GetCaseResponse, error)
	mustEmbedUnimplementedPoliceStorageServiceServer()
}

// UnimplementedPoliceStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoliceStorageServiceServer struct{}

func (UnimplementedPoliceStorageServiceServer) PutCase(context.Context, *CaseRequest) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCase not implemented")
}
func (UnimplementedPoliceStorageServiceServer) GetCase(context.Context, *GetCaseRequest) (*GetCaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCase not implemented")
}
func (UnimplementedPoliceStorageServiceServer) mustEmbedUnimplementedPoliceStorageServiceServer() {}
func (UnimplementedPoliceStorageServiceServer) testEmbeddedByValue()                              {}

// UnsafePoliceStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoliceStorageServiceServer will
// result in compilation errors.
type UnsafePoliceStorageServiceServer interface {
	mustEmbedUnimplementedPoliceStorageServiceServer()
}

func RegisterPoliceStorageServiceServer(s grpc.ServiceRegistrar, srv PoliceStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedPoliceStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoliceStorageService_ServiceDesc, srv)
}

func _PoliceStorageService_PutCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceStorageServiceServer).PutCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceStorageService_PutCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceStorageServiceServer).PutCase(ctx, req.(*CaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoliceStorageService_GetCase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoliceStorageServiceServer).GetCase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoliceStorageService_GetCase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoliceStorageServiceServer).GetCase(ctx, req.(*GetCaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PoliceStorageService_ServiceDesc is the grpc.ServiceDesc for PoliceStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoliceStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.PoliceStorageService",
	HandlerType: (*PoliceStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutCase",
			Handler:    _PoliceStorageService_PutCase_Handler,
		},
		{
			MethodName: "GetCase",
			Handler:    _PoliceStorageService_GetCase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/storage.proto",
}
